add initramfs mode

diff --git a/bin/update b/bin/update
--- a/bin/update
+++ b/bin/update
@@ -276,6 +276,10 @@ do
             OPT_MODE=kernel
             ;;
 
+        -i|--initramfs)
+            OPT_MODE=initramfs
+            ;;
+
         *)
             # unknown stuff
             ;;
@@ -401,6 +405,77 @@ then
     echo "Emerging kernel modules..."
     sleep 2
     emerge -tv --quiet-build @module-rebuild
+fi
+
+if [ "$OPT_MODE" == "initramfs" ]
+then
+    # TODO: lvm2 no longer static
+    exit 90
+
+    mount /boot || echo "/boot already mounted"
+    sleep 1
+    echo "/boot filesystem disk space usage:"
+    df -h | grep boot | egrep --color '[0-9]{1,2}%'
+    FREE_BOOT_SPACE_MB=$(df -BM --output=target,avail | grep boot | egrep -o '[0-9]+')
+    if [ "$FREE_BOOT_SPACE_MB" -lt "15" ]; then
+        read -n 1 -ep "Only $FREE_BOOT_SPACE_MB MB avaiable on /boot. Continue? (y/n) "
+        [[ "$REPLY" =~ ^[Nn]$ ]] && umount /boot && exit 0
+    fi
+
+    echo "$INITRAMFS_LIST" > /tmp/initramfs_list
+    echo "$INITRAMFS_INIT" > /tmp/initramfs_init
+    RUNNING_VERSION=$(uname -r)
+    RUNNING_DIR="linux-$RUNNING_VERSION"
+
+    cd /usr/src
+    NEXT_DIR=$(readlink linux)
+    NEXT_VERSION=${NEXT_DIR#"linux-"}
+    NEXT_INITRAMFS="initramfs-$NEXT_VERSION"
+
+    cd /usr/src/linux
+
+    # manually create initramfs from directory
+    #cd initram || die
+    #find . | cpio --quiet -o -H newc | gzip -9 > ../initramfs
+
+    # https://forums.gentoo.org/viewtopic-t-1014242-view-next.html?sid=9b262ff7daa08ca1b824b278364bcbbd
+    # emerge pax-utils USE=python
+    # lddtree  --copy-to-tree=/usr/src/initramfs     /sbin/cryptsetup
+
+    # Use gen_initramfs_list.sh to build initramfs
+    make -C /usr/src/linux/usr/ gen_init_cpio
+    chmod +x usr/gen_init_cpio scripts/gen_initramfs_list.sh
+    ./scripts/gen_initramfs_list.sh -o /tmp/initramfs /tmp/initramfs_list
+
+    # TODO: v86d causing problems somewhere around 3.18.11
+    #/usr/sbin/splash_geninitramfs --verbose --res 1280x1024 --append /tmp/initramfs Emergance
+
+    # TODO: both backup and current links can point to same files when kernel
+    # version doesn't change
+    mv -i --backup=numbered /tmp/initramfs "/boot/$NEXT_INITRAMFS"
+    cd /boot
+
+    echo 'Update backup symlinks to point to current?'
+    select yn in "Yes" "No";
+    do
+        case $yn in
+            Yes )
+                ls -l
+                ln -sfT "$(readlink initramfs)" initramfs.bak
+                ln -sfT "$NEXT_INITRAMFS" initramfs
+                ls -l
+                break;;
+            No )
+                ln -sfT "$NEXT_INITRAMFS" initramfs
+                break;;
+        esac
+    done
+
+    echo "/boot filesystem disk space usage:"
+    df -h | grep boot | egrep --color '[0-9]{1,2}%'
+    cd -
+    sleep 1
+    umount /boot || echo "/boot umount failed!"
 fi
 
 if [ "$OPT_MODE" == "world" ]
