update update

diff --git a/bin/update b/bin/update
--- a/bin/update
+++ b/bin/update
@@ -433,8 +433,8 @@ update_initramfs() {
 }
 
 update_world() {
-    emerge -tvu --quiet-build --autounmask-write --with-bdeps=y portage || ( revdep-rebuild -i && die "update portage failed" )
-    emerge -tvuND --quiet-build --backtrack=30 --autounmask-write --with-bdeps=y --complete-graph @world || ( revdep-rebuild -i && die "update world failed" )
+    emerge -tv1u --quiet-build --autounmask-write --with-bdeps=y portage || die "update portage failed"
+    emerge -tvuND --quiet-build --backtrack=30 --autounmask-write --with-bdeps=y --complete-graph @world || die "update world failed"
     if ! hash genlop || genlop -l --date yesterday | grep -q haskell
     then
         hash haskell-updater && haskell-updater
@@ -442,13 +442,17 @@ update_world() {
 
     if ! hash genlop || genlop -l --date yesterday | grep -q x11-base/xorg-server
     then
-        emerge -tv --quiet-build @x11-module-rebuild
+        emerge -t1v --quiet-build @x11-module-rebuild
     fi
 
-    emerge -tv --quiet-build --autounmask-write @preserved-rebuild
+    emerge -t1v --quiet-build --autounmask-write @preserved-rebuild
+    if hash smart-live-rebuild
+    then
+        smart-live-rebuild || die "smart-live-rebuild failed"
+    fi
+
     emerge -c
     revdep-rebuild -i -- --quiet-build
-    dispatch-conf
 }
 
 parse_options() {
@@ -468,6 +472,7 @@ parse_options() {
                 echo "       --eclean        Clean distfiles after updating world"
                 echo
                 echo "   -s, --only-sync     Only sync repos and exit"
+                echo "   -c, --config        Update config with dispatch-conf"
                 echo
                 echo "   -k, --kernel        Update kernel"
                 echo "       --eclean-kernel Clean kernels after updating kernel"
@@ -479,6 +484,10 @@ parse_options() {
                 ;;
             --no-sync)
                 OPT_SYNC=
+                ;;
+
+            -c|--config)
+                OPT_UPDATE_CONF=1
                 ;;
 
             -s|--only-sync)
@@ -541,6 +550,10 @@ main() {
 
         if [ -n "$OPT_ECLEAN" ]; then
             eclean --deep distfiles
+        fi
+
+        if [ -n "$OPT_UPDATE_CONF" ]; then
+            dispatch-conf
         fi
     fi
 }
